package com.kuark.jfzk.demo.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTBaseLog<M extends BaseTBaseLog<M>> extends Model<M> implements IBean {

    public void setId(java.lang.Long id) {
        set("id", id);
    }

    public java.lang.Long getId() {
        return get("id");
    }

    public void setFunctionId(java.lang.Long functionId) {
        set("function_id", functionId);
    }

    public java.lang.Long getFunctionId() {
        return get("function_id");
    }

    public void setContent(java.lang.String content) {
        set("content", content);
    }

    public java.lang.String getContent() {
        return get("content");
    }

    public void setUserId(java.lang.Long userId) {
        set("user_id", userId);
    }

    public java.lang.Long getUserId() {
        return get("user_id");
    }

    public void setGenTime(java.util.Date genTime) {
        set("gen_time", genTime);
    }

    public java.util.Date getGenTime() {
        return get("gen_time");
    }

}
