package com.kuark.jfzk.demo.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTBasePrivilege<M extends BaseTBasePrivilege<M>> extends Model<M> implements IBean {

    public void setId(java.lang.Long id) {
        set("id", id);
    }

    public java.lang.Long getId() {
        return get("id");
    }

    public void setName(java.lang.String name) {
        set("name", name);
    }

    public java.lang.String getName() {
        return get("name");
    }

    public void setDescription(java.lang.String description) {
        set("description", description);
    }

    public java.lang.String getDescription() {
        return get("description");
    }

    public void setType(java.lang.String type) {
        set("type", type);
    }

    public java.lang.String getType() {
        return get("type");
    }

    public void setUri(java.lang.String uri) {
        set("uri", uri);
    }

    public java.lang.String getUri() {
        return get("uri");
    }

    public void setOrdering(java.lang.Long ordering) {
        set("ordering", ordering);
    }

    public java.lang.Long getOrdering() {
        return get("ordering");
    }

    public void setParentId(java.lang.Long parentId) {
        set("parent_id", parentId);
    }

    public java.lang.Long getParentId() {
        return get("parent_id");
    }

    public void setLogFlag(java.lang.Boolean logFlag) {
        set("log_flag", logFlag);
    }

    public java.lang.Boolean getLogFlag() {
        return get("log_flag");
    }

    public void setStatus(java.lang.Integer status) {
        set("status", status);
    }

    public java.lang.Integer getStatus() {
        return get("status");
    }

}
