package com.kuark.jfzk.demo.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTAppConfig<M extends BaseTAppConfig<M>> extends Model<M> implements IBean {

    public void setId(java.lang.Integer id) {
        set("id", id);
    }

    public java.lang.Integer getId() {
        return get("id");
    }

    public void setModule(java.lang.String module) {
        set("module", module);
    }

    public java.lang.String getModule() {
        return get("module");
    }

    public void setKey(java.lang.String key) {
        set("key", key);
    }

    public java.lang.String getKey() {
        return get("key");
    }

    public void setType(java.lang.String type) {
        set("type", type);
    }

    public java.lang.String getType() {
        return get("type");
    }

    public void setValue(java.lang.String value) {
        set("value", value);
    }

    public java.lang.String getValue() {
        return get("value");
    }

    public void setDescription(java.lang.String description) {
        set("description", description);
    }

    public java.lang.String getDescription() {
        return get("description");
    }

}
