package com.kuark.jfzk.demo.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTBaseRole<M extends BaseTBaseRole<M>> extends Model<M> implements IBean {

    public void setId(java.lang.Long id) {
        set("id", id);
    }

    public java.lang.Long getId() {
        return get("id");
    }

    public void setName(java.lang.String name) {
        set("name", name);
    }

    public java.lang.String getName() {
        return get("name");
    }

    public void setDescription(java.lang.String description) {
        set("description", description);
    }

    public java.lang.String getDescription() {
        return get("description");
    }

    public void setStatus(java.lang.Integer status) {
        set("status", status);
    }

    public java.lang.Integer getStatus() {
        return get("status");
    }

}
