package com.kuark.jfzk.demo.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

    public static void mapping(ActiveRecordPlugin arp) {
        arp.addMapping("t_app_config", "id", TAppConfig.class);
        arp.addMapping("t_base_group", "id", TBaseGroup.class);
        arp.addMapping("t_base_group_privilege_relation", "id", TBaseGroupPrivilegeRelation.class);
        arp.addMapping("t_base_log", "id", TBaseLog.class);
        arp.addMapping("t_base_privilege", "id", TBasePrivilege.class);
        arp.addMapping("t_base_role", "id", TBaseRole.class);
        arp.addMapping("t_base_role_privilege_relation", "id", TBaseRolePrivilegeRelation.class);
        arp.addMapping("t_base_user", "id", TBaseUser.class);
        arp.addMapping("t_base_user_group_relation", "id", TBaseUserGroupRelation.class);
        arp.addMapping("t_base_user_role_relation", "id", TBaseUserRoleRelation.class);
    }
}

