package com.kuark.jfzk.demo.model;

import com.kuark.jfzk.demo.model.base.BaseTAppConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TAppConfig extends BaseTAppConfig<TAppConfig> {

}
