package com.kuark.jfzk.demo.model;

import com.kuark.jfzk.demo.model.base.BaseTBaseRolePrivilegeRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TBaseRolePrivilegeRelation extends BaseTBaseRolePrivilegeRelation<TBaseRolePrivilegeRelation> {

}
