package com.kuark.jfzk.demo.model;

import com.kuark.jfzk.demo.model.base.BaseTBaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TBaseRole extends BaseTBaseRole<TBaseRole> {

}
