package com.kuark.jfzk.demo.model;

import com.kuark.jfzk.demo.model.base.BaseTBasePrivilege;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TBasePrivilege extends BaseTBasePrivilege<TBasePrivilege> {

}
