package com.kuark.jfzk.demo.model;

import com.kuark.jfzk.demo.model.base.BaseTBaseGroupPrivilegeRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TBaseGroupPrivilegeRelation extends BaseTBaseGroupPrivilegeRelation<TBaseGroupPrivilegeRelation> {

}
