package com.kuark.jfzk.demo.model;

import com.kuark.jfzk.demo.model.base.BaseTBaseUserGroupRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TBaseUserGroupRelation extends BaseTBaseUserGroupRelation<TBaseUserGroupRelation> {

}
