package com.kuark.jfzk.demo.model;

import com.kuark.jfzk.demo.model.base.BaseTBaseGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TBaseGroup extends BaseTBaseGroup<TBaseGroup> {

}
