package com.kuark.jfzk.demo.model;

import com.kuark.jfzk.demo.model.base.BaseTBaseUserRoleRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TBaseUserRoleRelation extends BaseTBaseUserRoleRelation<TBaseUserRoleRelation> {

}
