package com.kuark.jfzk.demo.model;

import com.kuark.jfzk.demo.model.base.BaseTBaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TBaseUser extends BaseTBaseUser<TBaseUser> {

}
