package com.kuark.jfzk.demo.model;

import com.kuark.jfzk.demo.model.base.BaseTBaseLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TBaseLog extends BaseTBaseLog<TBaseLog> {

}
